### ISSUE TITLE
Determine how to embed application with javascript

### ISSUE THREAD

**Issue by gigibyte927** [gigibyte927/comments-4orum#3]
Figure out a solution for embedding comment app in other sites.

Look into safety of iframes.

**Comment by mark-craig** [comment]
I've been doing some research on this. As far as I can tell, there are two approaches that we can take.
1. IFrame Approach
* We use simply use an iframe, we make our site serve html responses with a front-end framework like Bootstrap.
([https://github.com/abersager/django-iframed](https://github.com/abersager/django-iframed))
* We use javascript or CSS to make the iframe responsive and mobile-ready ([https://benmarshall.me/responsive-iframes/](https://benmarshall.me/responsive-iframes/))

2. Injection Approach (probably much nicer)
* We no longer use an iframe, instead we write javascript code that injects html into a certain <div> with given id on the page. We request data from our site using AJAX calls, and update that div with the information we need. ([http://alexmarandon.com/articles/web_widget_jquery/](http://alexmarandon.com/articles/web_widget_jquery/))

**Caveats with this approach**
* From the link above, it sounds like we could serve html responses from our site "wrapped" in JSON. We may or may not want to do this, I think the most common approach would just be to get the data itself, and worry about the html within our script.
* If we are trying to inject html that looks nice into the page, we will need to use some CSS. In the tutorial above, the css file is just injected into the head of the page where the widget is being embedded. This could be problematic for us, if our CSS overrides the CSS originally on the page (e.g., we inject Bootstrap 4 into the header and the site uses Bootstrap 3), we could cause some serious problems for the site we are embedding into. I think the best solution to this problem would be to use something like this ([https://github.com/css-modules/css-modules](https://github.com/css-modules/css-modules)) to make sure our CSS is 'scoped' to just the html we are injecting, not the rest of the site. 
* For the problem above, it might also be prudent to use some front-end other than bootstrap that is much more lightweight (and doesn't need its own javascript in order to function). **Plus, if the framework doesn't use common div names like 'col' we might even be able to get away with injecting the link into the head directly**. Pure CSS looks like it could be perfect for our purposes ([https://purecss.io/](https://purecss.io/)) for these reasons. It's only one CSS file on its own, and the names for its divs seem to be prefixed with "pure-".

**Comment by mark-craig** [comment]
Forgot to mark this issue as closed. IFrame solution is temporarily implemented as a proof-of-concept, (final solution using React is in progress and can be found at [**this repo**](https://github.com/mark-craig/widget-4orum).
